export const MESSAGE_QUICK_REACTIONS = ["👍", "❤️", "😂", "😮", "😢", "👎"] as const;

export type MessageQuickReaction = (typeof MESSAGE_QUICK_REACTIONS)[number];

export type MessageEmojiOption = {
  emoji: string;
  keywords: string[];
};

export type MessageEmojiCategory = {
  label: string;
  emojis: MessageEmojiOption[];
};

function emoji(value: string, ...keywords: string[]): MessageEmojiOption {
  return { emoji: value, keywords };
}

export const MESSAGE_EMOJI_CATEGORIES: MessageEmojiCategory[] = [
  {
    label: "Frequently used",
    emojis: [
      emoji("👍", "thumbs", "up", "like", "yes"),
      emoji("❤️", "heart", "love", "red"),
      emoji("😂", "laugh", "joy", "lol", "funny"),
      emoji("😮", "wow", "surprised", "shocked"),
      emoji("😢", "sad", "cry", "tear"),
      emoji("👎", "thumbs", "down", "dislike", "no"),
      emoji("🔥", "fire", "hot", "lit"),
      emoji("🎉", "party", "celebrate", "tada"),
      emoji("👏", "clap", "applause"),
      emoji("🙏", "pray", "thanks", "please"),
      emoji("💯", "hundred", "perfect"),
      emoji("✨", "sparkle", "shine"),
    ],
  },
  {
    label: "Smileys",
    emojis: [
      emoji("😀", "grin", "happy", "smile"),
      emoji("😃", "smile", "happy"),
      emoji("😄", "smile", "laugh"),
      emoji("😁", "beam", "grin"),
      emoji("😆", "laugh", "squint"),
      emoji("😅", "sweat", "nervous", "laugh"),
      emoji("🤣", "rofl", "laugh", "rolling"),
      emoji("😊", "blush", "smile"),
      emoji("😇", "angel", "innocent"),
      emoji("🙂", "smile", "slight"),
      emoji("😉", "wink"),
      emoji("😍", "heart", "eyes", "love"),
      emoji("🥰", "love", "hearts", "adore"),
      emoji("😘", "kiss", "heart"),
      emoji("😋", "yum", "tongue", "delicious"),
      emoji("😜", "wink", "tongue", "playful"),
      emoji("🤪", "zany", "crazy", "silly"),
      emoji("🤔", "think", "hmm", "ponder"),
      emoji("😐", "neutral", "meh"),
      emoji("😑", "expressionless", "blank"),
      emoji("😏", "smirk"),
      emoji("🙄", "eyeroll", "whatever"),
      emoji("😬", "grimace", "awkward"),
      emoji("😴", "sleep", "tired", "zzz"),
      emoji("🤯", "mind", "blown", "explode"),
      emoji("🥳", "party", "celebrate"),
      emoji("😎", "cool", "sunglasses"),
      emoji("🤩", "star", "eyes", "excited"),
      emoji("😭", "cry", "sob", "sad"),
      emoji("😤", "steam", "angry", "frustrated"),
      emoji("😡", "angry", "mad", "rage"),
      emoji("🤬", "swear", "angry", "cursing"),
      emoji("😱", "scream", "fear", "shocked"),
      emoji("🥺", "pleading", "puppy", "eyes"),
      emoji("😳", "flushed", "embarrassed"),
      emoji("🤗", "hug", "warm"),
      emoji("🤭", "giggle", "oops"),
      emoji("🫶", "heart", "hands", "love"),
    ],
  },
  {
    label: "Gestures",
    emojis: [
      emoji("👋", "wave", "hello", "hi"),
      emoji("🤝", "handshake", "deal"),
      emoji("✌️", "peace", "victory"),
      emoji("🤞", "fingers", "crossed", "luck"),
      emoji("🤟", "love", "rock"),
      emoji("👌", "ok", "perfect"),
      emoji("🤌", "pinch", "italian"),
      emoji("👈", "point", "left"),
      emoji("👉", "point", "right"),
      emoji("👆", "point", "up"),
      emoji("👇", "point", "down"),
      emoji("☝️", "point", "one"),
      emoji("✋", "hand", "stop", "high five"),
      emoji("🖐️", "hand", "five"),
      emoji("🖖", "vulcan", "spock"),
      emoji("👊", "fist", "bump", "punch"),
      emoji("✊", "fist", "power"),
      emoji("🤛", "fist", "left"),
      emoji("🤜", "fist", "right"),
      emoji("🫡", "salute"),
      emoji("🫶", "heart", "hands"),
      emoji("💪", "muscle", "strong", "flex"),
    ],
  },
  {
    label: "Hearts",
    emojis: [
      emoji("❤️", "red", "heart", "love"),
      emoji("🧡", "orange", "heart"),
      emoji("💛", "yellow", "heart"),
      emoji("💚", "green", "heart"),
      emoji("💙", "blue", "heart"),
      emoji("💜", "purple", "heart"),
      emoji("🖤", "black", "heart"),
      emoji("🤍", "white", "heart"),
      emoji("🤎", "brown", "heart"),
      emoji("💔", "broken", "heart", "sad"),
      emoji("❤️‍🔥", "heart", "fire", "passion"),
      emoji("💕", "hearts", "love"),
      emoji("💞", "hearts", "revolving"),
      emoji("💓", "beating", "heart"),
      emoji("💗", "growing", "heart"),
      emoji("💖", "sparkling", "heart"),
      emoji("💘", "cupid", "arrow", "heart"),
      emoji("💝", "gift", "heart"),
    ],
  },
  {
    label: "Books & reading",
    emojis: [
      emoji("📚", "books", "library", "read"),
      emoji("📖", "book", "open", "read"),
      emoji("📕", "book", "red"),
      emoji("📗", "book", "green"),
      emoji("📘", "book", "blue"),
      emoji("📙", "book", "orange"),
      emoji("📓", "notebook"),
      emoji("📒", "ledger", "notebook"),
      emoji("📔", "notebook", "decorated"),
      emoji("📃", "page", "curl"),
      emoji("📜", "scroll", "parchment"),
      emoji("🔖", "bookmark"),
      emoji("🏷️", "label", "tag"),
      emoji("✍️", "write", "pen"),
      emoji("🖊️", "pen"),
      emoji("📝", "memo", "note", "write"),
      emoji("💡", "idea", "lightbulb"),
      emoji("🧠", "brain", "smart", "think"),
    ],
  },
  {
    label: "Animals",
    emojis: [
      emoji("🐶", "dog", "puppy"),
      emoji("🐱", "cat", "kitten"),
      emoji("🐭", "mouse"),
      emoji("🐹", "hamster"),
      emoji("🐰", "rabbit", "bunny"),
      emoji("🦊", "fox"),
      emoji("🐻", "bear"),
      emoji("🐼", "panda"),
      emoji("🐨", "koala"),
      emoji("🐯", "tiger"),
      emoji("🦁", "lion"),
      emoji("🐮", "cow"),
      emoji("🐷", "pig"),
      emoji("🐸", "frog"),
      emoji("🐵", "monkey"),
      emoji("🦄", "unicorn", "magic"),
      emoji("🐝", "bee"),
      emoji("🦋", "butterfly"),
      emoji("🐙", "octopus"),
      emoji("🦉", "owl"),
    ],
  },
  {
    label: "Food",
    emojis: [
      emoji("🍎", "apple", "red"),
      emoji("🍊", "orange", "fruit"),
      emoji("🍋", "lemon", "citrus"),
      emoji("🍌", "banana"),
      emoji("🍉", "watermelon"),
      emoji("🍇", "grapes"),
      emoji("🍓", "strawberry"),
      emoji("🫐", "blueberry"),
      emoji("🍕", "pizza"),
      emoji("🍔", "burger", "hamburger"),
      emoji("🍟", "fries"),
      emoji("🌮", "taco"),
      emoji("🍣", "sushi"),
      emoji("🍩", "donut", "doughnut"),
      emoji("🍪", "cookie"),
      emoji("🎂", "cake", "birthday"),
      emoji("🍰", "cake", "slice"),
      emoji("☕", "coffee"),
      emoji("🍵", "tea"),
      emoji("🍷", "wine"),
      emoji("🍺", "beer"),
      emoji("🥂", "champagne", "cheers"),
    ],
  },
  {
    label: "Symbols",
    emojis: [
      emoji("⭐", "star"),
      emoji("🌟", "star", "glow"),
      emoji("💫", "dizzy", "star"),
      emoji("✅", "check", "yes", "done"),
      emoji("❌", "x", "no", "wrong"),
      emoji("❓", "question"),
      emoji("❗", "exclamation"),
      emoji("‼️", "bangbang"),
      emoji("💬", "speech", "bubble", "chat"),
      emoji("💭", "thought", "bubble"),
      emoji("🔔", "bell", "notification"),
      emoji("🎵", "music", "note"),
      emoji("🎶", "music", "notes"),
      emoji("🏆", "trophy", "win"),
      emoji("🥇", "gold", "medal", "first"),
      emoji("🎯", "target", "bullseye"),
      emoji("♻️", "recycle"),
      emoji("⚡", "lightning", "zap"),
      emoji("🌈", "rainbow"),
      emoji("🌙", "moon", "night"),
      emoji("☀️", "sun", "sunny"),
    ],
  },
];

export const MESSAGE_EMOJI_OPTIONS = MESSAGE_EMOJI_CATEGORIES.flatMap(
  (category) => category.emojis
);
